#! /src/bin/env php

<?php

use Src\AddCommand;
use Src\Complete;
use Src\DatabaseAdapter;
use Src\ShowCommand;
use Symfony\Component\Console\Application;

require_once 'vendor/autoload.php';

$app = new Application('Tasks App', '1.0');

try {
    $pdo = new PDO('sqlite:db.sqlite');
    $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_ASSOC);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (Exception $e) {
    echo 'Could not connect to the database';
    exit(1);
}

$adapter = new DatabaseAdapter($pdo);

$app->add(new ShowCommand($adapter));

$app->add(new AddCommand($adapter));

$app->add(new Complete($adapter));

$app->run();