#! /usr/bin/env php

<?php

use Src\NewCommand;
use Src\UsersAllCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

require_once 'vendor/autoload.php';

$app = new Application('Laracast Demo', '1.0');

$app->add(new UsersAllCommand);

$app->add(new NewCommand(new GuzzleHttp\Client));

$app->run();